version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    networks:
      - my_network
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    networks:
      - my_network
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uzinfocom
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_php
    networks:
      - my_network
    volumes:
      - ./src:/var/www/html

    ports:
      - "8001:80"
      - "6001:6001"
      - "5173:5173"

    command: >
      bash -c "true
      && composer install
      && php artisan key:generate
      && php artisan migrate
      && php artisan cache:clear
      && php artisan optimize:clear
      && docker-php-entrypoint php-fpm
      "
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: customer_phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: laravel_mysql
      PMA_PORT: 3306
#      PMA_USER: root
#      PMA_PASSWORD: password
    depends_on:
      -   mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge