version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    networks:
      - my_network
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    networks:
      - my_network
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uzinfocom
#     MYSQL_USER: root
#     MYSQL_PASSWORD: password
#    volumes:
#      - ./docker/volumes/mysql:/var/lib/mysql



  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_php
    networks:
      - my_network
    volumes:
      - ./src:/var/www/html

    ports:
      - "6001:6001"
      - "5173:5173"

    command: >
      bash -c "true
      && composer install
      && php artisan key:generate
      && php artisan migrate
      && php artisan cache:clear
      && php artisan optimize:clear
      && supervisord -c /etc/supervisor/conf.d/supervisord.conf
      "
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: laravel_mysql
      PMA_PORT: 3306
#      PMA_USER: root
#      PMA_PASSWORD: password
    depends_on:
      -   mysql
    networks:
      - my_network


  loki:
    image: grafana/loki:latest
    container_name: laravel_loki
    ports:
      - "3100:3100"
#    volumes:
#      - ./docker/grafana/loki-config.yml:/etc/loki/loki.yml
    command: -config.file=/etc/loki/local-config.yaml
#    command: -config.file=/etc/loki/docker-config.yml
    networks:
      - my_network

  prom-tail:
    image: grafana/promtail:v1.3.0
    container_name: laravel_promtail
    #    volumes:
    #      - ./docker/grafana/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: laravel_grafana
    volumes:
      - ./:/var/www/html
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge