server:
  http_listen_port: 9080
  http_grpc_server_enabled: false

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'laravel'
    static_configs:
      - targets:
          - localhost
        labels:
          job: laravel
          __path__: /var/www/html/storage/log/laravel.log  # Laravel logining to'liq yo'li
